version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - AWS_REGION
      - AWS_BUCKET
      - AWS_BUCKET_FOLDER
      - AWS_KEY
      - AWS_SECRET
      - CORS
      - DATABASE
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_DEFAULT
      - NEXTAUTH_EXPRIRY
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - NODE_ENV=production
    restart: unless-stopped
